#!/usr/bin/env python2.7

#report zuma version per exit status

import sys
import  zuma_config

def main():
    

    if zuma_config.params.vpr7 is True:
        sys.exit(1)
    
    sys.exit(0)

if __name__ == "__main__":
    main()